name: troika-nf
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython=1.79
  - delly=0.8.7
  - iqtree=1.6.12
  - jinja2=3.0.1
  - kraken2=2.1.2
  - mash=2.3
  - mtb-snp-it=1.1
  - pandas=1.3.0
  - python=3
  - samclip=0.4.0
  - samtools=1.12
  - seqkit=0.16.1
  - seqtk=1.3
  - snakemake=6.4.1
  - snippy=4.5
  - snpeff=5.0
  - snp-dists=0.7.0
  - snp-sites=2.5.1
  - tb-profiler=2.8.14
  - trimmomatic=0.39
  - vt=2015.11.10
  - pip:
      - git+https://github.com/BCCDC-PHL/troika.git
